# Keys required for search.py

# Google
GOOGLE_KEY = #INSERT YOUR API KEY HERE#

# Twitter
TWITTER_CONSUMER_KEY = #INSERT YOUR API KEY HERE#
TWITTER_SECRET_KEY = #INSERT YOUR API KEY HERE#
ACCESS_TOKEN = #INSERT YOUR API KEY HERE#
ACCESS_TOKEN_SECRET = #INSERT YOUR API KEY HERE#

# Reddit
REDDIT_CLIENT_ID = #INSERT YOUR API KEY HERE#
REDDIT_CLIENT_SECRET = #INSERT YOUR API KEY HERE#

# news
NEWS_KEY = #INSERT YOUR API KEY HERE#
